name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41bfe87238e56d947f2cec3d3a1d1bf8732c0ffaa7cb04bf23b2b9d73fc3fcac"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
